### ISSUE TITLE
Missing file - bin/archive-download.py - from recent rebase

### ISSUE THREAD

**Issue by pndiku** [akissa/baruwa2#59]
This file is referenced in ```setup.py```. Setup runs if I remove the line but not sure what the final impact will be

**Comment by akissa** [comment]
No impact, removed in 0307b5daefd4b7a2014df3914d9af51a4cb2a291

**Comment by pndiku** [comment]
Decided to add to this bug-report rather than opening several others.

Finished the install and the web interface is missing several public files (so far) such as:
``/css/baruwa.login.min.css``
``/js/baruwa/common.min.js``

Also, from reading the Enterprise documentation, it seems that ```updatedelta.ini``` is part of the baruwa-uwsgi rpm. Is the updatedelta functionality meant to also be part of community edition?

**Comment by akissa** [comment]
You may have to build the css/js files.

The js is written in coffeescript, you should compile those to js using coffeescript.

The css is written in sass using compass, you need to compile the css using compass.

The updatedelta.ini is for a perl script that does indexing in a cluster which is not part of the community edition, you can use the paster update-delta-index which does the same thing.

**Comment by pndiku** [comment]
Ok, I'll look into that.

One other question: jsi18n.js. I've seen this error in the community edition for a long time but ignored it since I use baruwa in English. Where is that file?

Also... Is there a way to get these questions sorted outside of a github bug report?

**Comment by akissa** [comment]
jsi18n.js is not a file, it is generated dynamically.

https://github.com/akissa/baruwa2/blob/master/baruwa/config/routing.py#L61
https://github.com/akissa/baruwa2/blob/master/baruwa/controllers/utils.py

You could post them to the mailing list, however do not expect any speedy responses from me due to other pressures. You would be better served by going through the source code.

If the issue is caused by incomplete code then i will patch in were necessary, with this rebase i expect that the community edition will take on a life of its own as a truely community edition.

**Comment by fluxlabs** [comment]
I manually adjusted the path to fix the error. The file was not being dynamically generated. (I've never seen it work properly after install. )
--
Jeremy McSpadden | Flux Labs
Local - 850-250-5590x501<tel:850-250-5590;501> | Mobile - 850-890-2543<tel:850-890-2543>
Fax - 850-254-2955<tel:850-254-2955> | Toll Free - 877-699-FLUX<tel:877-699-FLUX>
Web - http://www.fluxlabs.net<http://www.fluxlabs.net/>


On Aug 29, 2015, at 9:55 AM, Andrew Colin Kissa <notifications@github.com<mailto:notifications@github.com>> wrote:


jsi18n.js is not a file, it is generated dynamically.

https://github.com/akissa/baruwa2/blob/master/baruwa/config/routing.py#L61
https://github.com/akissa/baruwa2/blob/master/baruwa/controllers/utils.py

You could post them to the mailing list, however do not expect any speedy responses from me due to other pressures. You would be better served by going through the source code.

If the issue is caused by incomplete code then i will patch in were necessary, with this rebase i expect that the community edition will take on a life of its own as a truely community edition.

-

**Comment by pndiku** [comment]
Thanks for the rebase, Andrew. I'm going to fork the code and run with it. I'm sure there's a lot of community interest.

**Comment by extremeshok** [comment]
@pndiku contacting you on skype

**Comment by akissa** [comment]
On 29 Aug 2015, at 5:07 PM, Peter C. Ndikuwera <notifications@github.com> wrote:

> Thanks for the rebase, Andrew. I'm going to fork the code and run with it. I'm sure there's a lot of community interest.

Great.
